on:
  push:
    branches: main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        run: composer install

      - name: Migrate DB
        run: |
          retries=3
          while [ $retries -gt 0 ]; do
            php artisan migrate --force && break
            sleep $((4 - retries))  # Экспоненциальная задержка
            retries=$((retries - 1))
          done
        env:
          APP_ENV: production
          DB_CONNECTION: postgresql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 5432
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt
        timeout-minutes: 100  # Перенесено на уровень выше блока env

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --env APP_KEY=${{ secrets.APP_KEY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        timeout-minutes: 100  # Перенесено на уровень выше блока env
